name: Python package

on:

  push:

    branches:

      - main

      - qa

      - develop


jobs:

  build:

    environment:

      name: Development

    runs-on: ubuntu-latest



steps:

  - uses: actions/checkout@v3

    with:

      fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags


  - name: Set up Python 3.7

    uses: actions/setup-python@v4

    with:

      python-version: "3.7"


  - name: DisplayPythonversion

    run: python -c "import sys; print(sys.version)"
